import random
from typing import Self

import polars as pl
from datasets import Dataset
from pydantic import BaseModel, Field
from tinker_cookbook.renderers.base import (
    Message,
    Role,
    TextPart,
    ThinkingPart,
    ToolCall,
    UnparsedToolCall,
)

from adapter_agent.hierarchical.types import Task
from adapter_agent.savable import Savable

TinkerMessage = Message


class QA(BaseModel):
    question: str
    answer: str


class QRA(QA):
    reasoning: str

    def to_tinker_messages(self) -> list[TinkerMessage]:
        return [
            TinkerMessage(role="user", content=self.question),
            TinkerMessage(
                role="assistant",
                content=[
                    ThinkingPart(type="thinking", thinking=self.reasoning),
                    TextPart(type="text", text=self.answer),
                ],
            ),
        ]


class QRADataset(BaseModel):
    problems: list[QRA]

    def as_prompt_completion(self) -> Dataset:
        prompt = []
        completion = []
        for sample in self.problems:
            prompt.append(sample.question)
            completion.append(
                f"<think>\n{sample.reasoning}\n</think>\n\n{sample.answer}"
            )
        dataframe = pl.DataFrame({"prompt": prompt, "completion": completion})
        return Dataset.from_polars(dataframe)

    def as_conversational(self) -> Dataset:
        items = [
            {
                "messages": [
                    {
                        "role": "user",
                        "content": sample.question,
                    },
                    {
                        "role": "assistant",
                        "content": f"<think>{sample.reasoning}</think>{sample.answer}",
                    },
                ]
            }
            for sample in self.problems
        ]
        return Dataset.from_list(items)

    def sort(self) -> Self:
        return self.__class__(problems=sorted(self.problems, key=lambda x: x.question))

    def head(self, n: int) -> Self:
        return self.__class__(problems=self.problems[:n])


class SFTDataset[T: BaseModel](Savable):
    items: list[T] = []

    def train_test_split(
        self, train_ratio: float, seed: int | None = None
    ) -> tuple[Self, Self]:
        copied = [item.model_copy(deep=True) for item in self.items]
        random.seed(seed)
        random.shuffle(copied)
        n_train = int(len(copied) * train_ratio)
        train = copied[:n_train]
        eval = copied[n_train:]
        return self.__class__(items=train), self.__class__(items=eval)

    def shuffled(self) -> list[T]:
        items = [item.model_copy(deep=True) for item in self.items]
        random.shuffle(items)
        return items


class QASFTDataset(SFTDataset[QA]):
    async def register(self, item: QA) -> None:
        self.items.append(item)


SerializableContentPart = TextPart | ThinkingPart


class PydanticTinkerBaseMessage(BaseModel):
    """
    Container for a single turn in a multi-turn conversation.

    Args:

    role: Role
        String that denotes the source of the message, typically system, user, assistant, and tool.
    content: Content
        Content of the message, can be a string, or a list of ContentPart.
        When content is a list, it can contain TextPart, ImagePart, and ThinkingPart elements.
        ThinkingPart represents the model's internal reasoning (chain-of-thought).
    tool_calls: NotRequired[list[ToolCall]]
        Optional sequence of successfully parsed tool calls generated by the model.
    unparsed_tool_calls: NotRequired[list[UnparsedToolCall]]
        Optional sequence of tool calls that failed to parse (e.g., invalid JSON).
        The raw text is preserved for debugging or re-rendering.
    trainable: NotRequired[bool]
        Optional indicator whether this message should contribute to the training loss.
    tool_call_id: NotRequired[str]
        For tool result messages (role="tool"): ID correlating this result to a specific
        tool call. Used by renderers whose wire format references calls by ID (e.g., Kimi K2
        renders "## Return of {tool_call_id}"). The value should match ToolCall.id from the
        assistant's tool_calls. Not all formats use IDs - GptOss/Harmony does not.
    name: NotRequired[str]
        For tool result messages (role="tool"): The function name that was called.
        Required by GptOss (renders "<|start|>functions.{name}..."), optional for others.
        When constructing tool results, include both name and tool_call_id when available
        since different renderers require different fields.

    """

    role: Role
    content: str | list[SerializableContentPart]

    tool_calls: list[ToolCall] | None = Field(default=None)
    unparsed_tool_calls: list[UnparsedToolCall] | None = Field(default=None)
    trainable: bool | None = Field(default=None)
    tool_call_id: str | None = Field(default=None)
    name: str | None = Field(default=None)
    knowledge_id: str | None = Field(default=None)
    cited_turn: int | None = Field(default=None)

    def to_tinker_message(self) -> TinkerMessage:
        input_dict = self.model_dump()
        input_dict["tool_calls"] = self.tool_calls or []
        input_dict.pop("trainable")
        return TinkerMessage(**input_dict)


class TinkerMessageTrajectory(BaseModel):
    task: Task
    messages: list[PydanticTinkerBaseMessage]

    def to_tinker_messages(self) -> list[TinkerMessage]:
        return [message.to_tinker_message() for message in self.messages]


class TinkerMessagesDataset(SFTDataset[TinkerMessageTrajectory]):
    def id_unique(self) -> Self:
        ids = set()
        unique_trajectories = []
        for trajectory in self.items:
            trajectory_id = hash(trajectory.model_dump_json())
            if trajectory_id not in ids:
                ids.add(trajectory_id)
                unique_trajectories.append(trajectory)
        return self.__class__(items=unique_trajectories)
